#Lee los datos de la persona
identificacion=input ("Ingrese el numero de identificacion de la persona: ")
nombre_P=input ("Ingrese el nombre de la persona sin apellidos: ")
apellido_P=input ("Ingrese los apellidos de la persona: ")
direccion_P=input ("Ingrese la direccion de la persona: ")
telefono_P=input ("Ingrese el numero de telefono: ")
edad_P=input ("Ingrese la edad de la persona en numeros: ")
estado_Civil=input ("Ingrese el estado civil de la persona: ")
numero_Hijos=input ("Ingrese el numero de hijos: ")
estatura=input ("Ingrese la estatura en centimetros: ")
fecha_Contratacion=input ("Ingrese la fecha de contratacion con el siguiente formato DD/MM/AAAA: ")
sueldo_Basico=input ("Ingrese el sueldo basico: ")
dias_Laborados=input ("Ingrese los dias laborados: ")
#Muestra los datos ingresados
print(identificacion)
print(nombre_P)
print(apellido_P)
print(direccion_P)
print(telefono_P)
print(edad_P)
print(estado_Civil)
print(numero_Hijos)
print(estatura)
print(fecha_Contratacion)
print(sueldo_Basico)
print(dias_Laborados)